<div class="clear"></div>
<hr>

<h1>
    <strong><?php echo CMPOPFLY_NAME; ?> Version</strong>
</h1>

<p>
    If you like the <?php echo CMPOPFLY_NAME; ?>  but you're missing some features, probably you can find it in the Premium version.
    <br/>
    We have prepared lists of features which you can find in one of the Premium versions of <a title="<?php echo CMPOPFLY_NAME; ?>" href="<?php echo CMPOPFLY_URL; ?>"><?php echo CMPOPFLY_NAME; ?></a>.
</p>

<div class="clear"></div>

<style type="text/css">
    .column{float: left; max-width: 30%; min-width: 510px; padding: 0 1%;}
    .column.first{padding-left: 0}
    .column ul li{margin-bottom: 15px}
    .new-item:before{
        content: 'New';
        background-color: #669834;
        padding: 8px;
        font-weight: bold;
        color: #FFF;
        float: left;
        margin-right: 5px;}
    .column p{
        font-weight: bold;
        padding: 5px 0;
        font-size: 16px;
        border-bottom: 1px solid #BBB;
    }
</style>

<div class="column first">
    <h2><?php echo CMPOPFLY_NAME; ?> Pro Edition <a href="<?php echo CMPOPFLY_URL; ?>" class="button button-primary">Buy</a></h2>
    <p>Includes all Free edition features + the following:</p>
    <ul>
        <li><strong>AdDesigner</strong> - The <?php echo CMPOPFLY_NAME; ?> Pro edition gives you the ability to use the simple WYSIWYG editor to generate the content of your Ads.</li>
        <li><strong>Statistics</strong> - Gather the statistics about the views and clicks of your Campaings. Display them in a table or as a graph!</li>
        <li><strong>Restrict by Page/Post/Url</strong> - The Pro edition allows you to display the Campaign on selected pages only, or on urls matching the pattern.</li>
        <li><strong>Restrict by Period</strong> - The Pro edition allows you to restrict the display the campaign in the limited timeframe, or timeframes!</li>
        <li><strong>Random Campaigns</strong> - In the Pro version you can choose the campaign to display random banner.</li>
        <li><strong>Custom Effects</strong> - Pro version allows you to choose the effect of displaying the Pop-Up/Fly-In banner.</li>
        <li><strong>Option to add the delay</strong> - While the free version only allows you to only show the message right after the page fully loads. In Pro you can define the delay.</li>
        <li><strong>Option to setup the display interval</strong> - The <?php echo CMPOPFLY_NAME; ?> Pro edition allows to only display given campaign once and not with each visit.</li>
    </ul>
</div>

<div class="clear"></div>